const startingGear = {
  swordsman: {
    hand: {
      name: "Broken Sword",
      ilvl: 1,
      rarity: "normal",
      requirements: { level: 1 },
      baseMods: [
        {
          modId: "physical_damage",
          description: "Physical Damage: # to #",
          values: [2, 3],
        },
        {
          modId: "critical_strike_chance",
          description: "Critical Strike Chance: #%",
          values: [4],
        },
      ],
      implicits: [],
      slot: "hand",
    },
    offhand: null,
    helmet: null,
    chest: {
      name: "Rusted Plate Armor",
      ilvl: 1,
      rarity: "normal",
      requirements: { level: 1 },
      baseMods: [{ modId: "armor", description: "Armor: #", values: [6] }],
      implicits: [],
      slot: "chest",
    },
    gloves: null,
    boots: null,
    ring_1: null,
    ring_2: null,
    amulet: null,
    belt: null,
  },
  ranger: {
    hand: {
      name: "Short Bow",
      ilvl: 1,
      rarity: "normal",
      requirements: { level: 1 },
      baseMods: [
        {
          modId: "physical_damage",
          description: "Physical Damage: # to #",
          values: [2, 4],
        },
        {
          modId: "critical_strike_chance",
          description: "Critical Strike Chance: #%",
          values: [5],
        },
      ],
      implicits: [],
      slot: "hand",
    },
    offhand: null,
    helmet: null,
    chest: {
      name: "Torn Leather Tunic",
      ilvl: 1,
      rarity: "normal",
      requirements: { level: 1 },
      baseMods: [{ modId: "evasion", description: "Evasion: #", values: [6] }],
      implicits: [],
      slot: "chest",
    },
    gloves: null,
    boots: null,
    ring_1: null,
    ring_2: null,
    amulet: null,
    belt: null,
  },
  sorcerer: {
    hand: {
      name: "Branch",
      ilvl: 1,
      rarity: "normal",
      requirements: { level: 1 },
      baseMods: [
        {
          modId: "physical_damage",
          description: "Physical Damage: # to #",
          values: [1, 3],
        },
        {
          modId: "critical_strike_chance",
          description: "Critical Strike Chance: #%",
          values: [4],
        },
      ],
      implicits: [
        {
          modId: "cold_damage_to_spells",
          description: "Adds # to # Cold Damage to Spells",
          values: [1, 2],
        },
      ],
      slot: "hand",
    },
    offhand: null,
    helmet: null,
    chest: {
      name: "Ragged Cloth",
      ilvl: 1,
      rarity: "normal",
      requirements: { level: 1 },
      baseMods: [{ modId: "evasion", description: "Evasion: #", values: [3] }],
      implicits: [],
      slot: "chest",
    },
    gloves: null,
    boots: null,
    ring_1: null,
    ring_2: null,
    amulet: null,
    belt: null,
  },
  assassin: {
    hand: {
      name: "Rusty Dagger",
      ilvl: 1,
      rarity: "normal",
      requirements: { level: 1 },
      baseMods: [
        {
          modId: "physical_damage",
          description: "Physical Damage: # to #",
          values: [2, 4],
        },
        {
          modId: "critical_strike_chance",
          description: "Critical Strike Chance: #%",
          values: [7],
        },
      ],
      implicits: [],
      slot: "hand",
    },
    offhand: null,
    helmet: null,
    chest: {
      name: "Leather Harness",
      ilvl: 1,
      rarity: "normal",
      requirements: { level: 1 },
      baseMods: [
        { modId: "evasion", description: "Evasion: #", values: [4] },
        { modId: "armor", description: "Armor: #", values: [2] },
      ],
      implicits: [],
      slot: "chest",
    },
    gloves: null,
    boots: null,
    ring_1: null,
    ring_2: null,
    amulet: null,
    belt: null,
  },
};

export default startingGear;
