version: "3.8"

services:
  mongodb_container:
    image: mongo:latest
    # environment:
    # MONGO_INITDB_ROOT_USERNAME: root
    # MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  # haproxy:
  #   build: ./game-server/haproxy
  #   links:
  #     - server-john
  #     - server-paul
  #     - server-george
  #     - server-ringo
  #   ports:
  #     - "4000:80"

  api:
    build: ./api
    ports:
      - "3000:3000"

  server-john:
    build: ./game-server
    # links:
    #   - redis
    ports:
      - "4000:4000"
    environment:
      - NAME=John

  # server-paul:
  #   build: ./game-server
  #   links:
  #     - redis
  #   expose:
  #     - "4000"
  #   environment:
  #     - NAME=Paul

  # server-george:
  #   build: ./game-server
  #   links:
  #     - redis
  #   expose:
  #     - "4000"
  #   environment:
  #     - NAME=George

  # server-ringo:
  #   build: ./game-server
  #   links:
  #     - redis
  #   expose:
  #     - "4000"
  #   environment:
  #     - NAME=Ringo

  # redis:
  #   image: redis:alpine
  #   expose:
  #     - "6379"

volumes:
  mongodb_data_container:
